name: DockerTest

on: [push]
jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: docker/build-push-action@v2
      with:
        tags: gadal-example:latest
        push: false
        secrets: |
          "gadal_github_key=${{ secrets.SGIDAL_CLONE_KEY_LINE }}"
    - uses: addnab/docker-run-action@v3
      with:
        image: gadal-example:latest
        run: echo "test"
