name: DockerTest

on: [push]
jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
    - name: build docker container
      shell: bash
      run: |
        docker build --progress=plain -t oedisi-example:0.0.0 .
      env:
        SSH_KEY: ${{secrets.SGIDAL_CLONE_KEY}}
        DOCKER_BUILDKIT: '1'
    - name: run docker continaer
      shell: bash
      run: |
        mkdir outputs_build
        docker volume create --name oedisi_output --opt type=none --opt device=$(pwd)/outputs_build --opt o=bind
        docker run --rm --mount source=oedisi_output,target=/simulation/outputs oedisi-example:0.0.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Run plots
      shell: bash -l {0}
      run: |
        pip install matplotlib pyarrow numpy matplotlib pandas
        pip install 'oedisi>=2,<3'

        oedisi evaluate-estimate --metric MAAE --path outputs
        oedisi evaluate-estimate --metric MARE --path outputs

        python post_analysis.py outputs_build
    - name: Archive logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker_logs
        path: |
          outputs_build/*.log
          *.png
