name: RunExample

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
        #include:
          #- os: ubuntu-latest
            #python-version: 3.10

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.CI_TOKEN }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      shell: bash -l {0}
      run: |
        pip install -r requirements.txt
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.SGIDAL_CLONE_KEY }}'
        pip install git+ssh://git@github.com/openEDI/GADAL.git@v0.2.1
    - name: Run example
      shell: bash -l {0}
      run: |
        python test_full_systems.py
        helics run --path=build/test_system_runner.json
        python post_analysis.py
    - name: Archive logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test_logs
        path: |
          *.png
          build/*.log
