name: TestLocalFeeder

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
        #include:
          #- os: ubuntu-latest
            #python-version: 3.10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      shell: bash -l {0}
      run: |
        pip install -r requirements.txt
        pip install plotille pytest
    - name: Run pytest on LocalFeeder
      shell: bash -l {0}
      run: |
        cd LocalFeeder
        pytest -W error -s .
      env:
        PYTEST_ADDOPTS: "--color=yes"
        PYTHONIOENCODING: UTF-8
