name: RunExample

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
        #include:
          #- os: ubuntu-latest
            #python-version: 3.10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      shell: bash -l {0}
      run: |
        pip install helics==3.1.2.post7
        pip install helics-apps==3.1.0
        pip install git+https://github.com/GMLC-TDC/helics-cli.git@main
        pip install pydantic
        pip install pyarrow
        pip install scipy matplotlib numpy pandas
        pip install 'OpenDSSDirect.py[extras]'
        pip install boto3
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.SGIDAL_CLONE_KEY }}'
        pip install git+ssh://git@github.com/openEDI/SGIDAL.git@main
    - name: Run example
      shell: bash -l {0}
      run: |
        python test_full_systems.py
        helics run --path=test_system_runner.json
        python post_analysis.py
    - name: Archive logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test_logs
        path: |
          *.png
          *.log
